imports:
    - { resource: services/ }

framework:
    router:
        resource: '%kernel.project_dir%/config/routings/'
        type: directory

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/AppKernel.php'
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
